### ISSUE TITLE
关于md5加密

### ISSUE THREAD

**Issue by zerozayu** [doersa/alfred-hash#2]
你好，我是个菜鸡（先表明立场我很菜
    我在使用你的这个hash的workflow时，遇到了一些错误，这个错误跟我使用在线网站[md5](http://www.md5.cz/)时遇到的情况一模一样。
    当我需要进行md5计算的串中包含了某些的键值对且用‘&’操作符连接的时候，该计算结果会出错，且结果是第一个‘&’操作符之前的串产生的结果。该网站是用http直接请求另一个网站，其实比较好的方式是调用本地zsh或者bash使用本地命令进行计算。

**Comment by zerozayu** [comment]
![Uploading QQ20220207-170418@2x.png…]()

**Comment by doersa** [comment]
感谢你的反馈，我会尽快修复这个问题。

**Comment by doersa** [comment]
Hi @zerozayu，已经修复这个问题，可以从release中更新了。
